var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":160,"id":40497,"methods":[{"el":58,"sc":2,"sl":44},{"el":80,"sc":2,"sl":70},{"el":85,"sc":2,"sl":82},{"el":141,"sc":2,"sl":87},{"el":159,"sc":2,"sl":143}],"name":"FPMLParserTest","sl":42}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_601":{"methods":[{"sl":87}],"name":"testGetSwapProductDescriptor[file=/Users/fries/git/finmath-lib/target/checkout/target/clover/test-classes/net/finmath/modelling/descriptor/xmlparser/ird-ex01-vanilla-swap.xml}]","pass":true,"statements":[{"sl":90},{"sl":91},{"sl":92},{"sl":93},{"sl":95},{"sl":97}]},"test_868":{"methods":[{"sl":87}],"name":"testGetSwapProductDescriptor[file=/Users/fries/git/finmath-lib/target/checkout/target/clover/test-classes/net/finmath/modelling/descriptor/xmlparser/ird-ex01-vanilla-swap.xml}]","pass":true,"statements":[{"sl":90},{"sl":91},{"sl":92},{"sl":93},{"sl":95},{"sl":97}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [601, 868], [], [], [601, 868], [601, 868], [601, 868], [601, 868], [], [601, 868], [], [601, 868], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]