var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":31,"id":14050,"methods":[{"el":25,"sc":2,"sl":22},{"el":30,"sc":2,"sl":27}],"name":"RandomVariableLazyEvaluationFactory","sl":15}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_14":{"methods":[{"sl":27}],"name":"testGetQuantile[net.finmath.montecarlo.RandomVariableLazyEvaluationFactory@3eb738bb]","pass":true,"statements":[{"sl":29}]},"test_282":{"methods":[{"sl":27}],"name":"testRandomVariableArithmeticSquaredPow[net.finmath.montecarlo.RandomVariableLazyEvaluationFactory@3eb738bb]","pass":true,"statements":[{"sl":29}]},"test_292":{"methods":[{"sl":27}],"name":"testRandomVariableArithmeticSqrtPow[net.finmath.montecarlo.RandomVariableLazyEvaluationFactory@3eb738bb]","pass":true,"statements":[{"sl":29}]},"test_301":{"methods":[{"sl":27}],"name":"testRandomVariableStochastic[net.finmath.montecarlo.RandomVariableLazyEvaluationFactory@3eb738bb]","pass":true,"statements":[{"sl":29}]},"test_388":{"methods":[{"sl":27}],"name":"testRandomVariableStandardDeviation[net.finmath.montecarlo.RandomVariableLazyEvaluationFactory@3eb738bb]","pass":true,"statements":[{"sl":29}]},"test_475":{"methods":[{"sl":27}],"name":"testAdd[net.finmath.montecarlo.RandomVariableLazyEvaluationFactory@3eb738bb]","pass":true,"statements":[{"sl":29}]},"test_50":{"methods":[{"sl":22}],"name":"testRandomVariableDeterministc[net.finmath.montecarlo.RandomVariableLazyEvaluationFactory@3eb738bb]","pass":true,"statements":[{"sl":24}]},"test_506":{"methods":[{"sl":27}],"name":"testFloor[net.finmath.montecarlo.RandomVariableLazyEvaluationFactory@3eb738bb]","pass":true,"statements":[{"sl":29}]},"test_507":{"methods":[{"sl":27}],"name":"testCap[net.finmath.montecarlo.RandomVariableLazyEvaluationFactory@3eb738bb]","pass":true,"statements":[{"sl":29}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [50], [], [50], [], [], [292, 14, 507, 475, 388, 282, 506, 301], [], [292, 14, 507, 475, 388, 282, 506, 301], [], []]